steps:

  # Install node packages
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'install' ]
    dir: 'boost-award/frontend'

  # Build productive files
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'run', 'build:ssr' ]
    dir: 'boost-award/frontend'

  # Deploy to google cloud app egnine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--version=prod']
    dir: 'boost-award/frontend'